/**
 * Skin generator: `themes/*.json` (4 seed colors) → `generated/*.css`.
 *
 * This script owns the two things that need a filesystem: reading upstream's
 * `design-platform.css` and writing the generated tree. The colour math itself
 * lives in `src/skins/derive.ts`, because a custom skin derives its palette in
 * the browser from a photograph the user picked, and a second implementation
 * of the ramp would be a second set of contrast bugs. One derivation, three
 * callers: this script, the Host boot transform, and the browser.
 *
 * The parse result is emitted as `generated/stock.ts` for exactly that reason —
 * the browser cannot read a CSS file off disk, so it reads the numbers this
 * script already extracted.
 *
 * Usage: node --import tsx/esm scripts/build-skins.mjs [--check]
 *   --check  verify the working tree matches what the generator would write
 *            (exit 1 on drift) instead of writing files.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { hexToOklch, parseColor } from '../src/skins/color.ts'
import { auditSkin, deriveSkin, CONTRACT, CHROME_CONTRACT } from '../src/skins/derive.ts'
import { renderSkinCss } from '../src/skins/render.ts'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const SKINS = `${ROOT}src/styles/skins`
const THEMES = `${SKINS}/themes`
const OUT = `${SKINS}/generated`
const PLATFORM = `${ROOT}src/styles/design-platform.css`

const check = process.argv.includes('--check')

// ── upstream palette ────────────────────────────────────────────────────────

/**
 * Read the stock palette out of design-platform.css. The palette is absolute —
 * both scheme blocks declare identical steps, and the schemes diverge only at
 * the semantic layer — so every static declaration in the file is read and the
 * families are keyed by name.
 * @returns `{ families, hex }` — steps grouped by family in OKLCh, plus the raw
 *          hex of every step.
 */
function readStockPalette() {
  const src = readFileSync(PLATFORM, 'utf8')
  const hex = {}
  const families = {}
  for (const m of src.matchAll(/(--dsw-static-[a-z0-9-]+)\s*:\s*([^;]+);/g)) {
    const name = m[1]
    if (hex[name] !== undefined) continue
    const value = m[2].trim()
    hex[name] = `#${parseColor(value).map(c => c.toString(16).padStart(2, '0')).join('')}`
    const family = name.replace(/-\d+(-delete)?$/, '')
    const [L, C, h] = hexToOklch(value)
    families[family] ??= []
    families[family].push({ name, L, C, h })
  }
  for (const steps of Object.values(families)) steps.sort((a, b) => b.L - a.L)
  return { families, hex }
}

/**
 * Read upstream's semantic layer for both schemes. These declarations are
 * mostly `var(--dsw-static-*)` references, so resolving them against a skin's
 * palette yields the colours that skin actually paints — which is what the
 * readability audit has to measure, rather than a proxy palette step.
 * @returns `{ light, dark }`, each token name → raw declaration.
 */
function readStockAliases() {
  const src = readFileSync(PLATFORM, 'utf8')
  const light = {}
  const dark = {}
  for (const m of src.matchAll(/(body(?:\[data-ds-dark-theme\])?)\s*\{(.*?)\n\}/gs)) {
    const target = m[1].includes('dark') ? dark : light
    for (const decl of m[2].matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/g)) {
      if (decl[1].startsWith('--dsw-static-')) continue
      target[decl[1]] = decl[2].trim()
    }
  }
  return { light, dark }
}

// ── emit ────────────────────────────────────────────────────────────────────

const BANNER = `/* GENERATED by scripts/build-skins.mjs — do not edit.
 * Source of truth: src/styles/skins/themes/<id>.json
 * Regenerate: pnpm --filter @deepseek-ai/dsh-client-ui-theme build:skins */`

/**
 * Compose one skin's sheet. The rules themselves come from `src/skins/render.ts`
 * so the Host and the browser emit the same shape for a custom skin; this
 * script only adds the banner and resolves heroes to bundler-relative paths.
 */
function renderSkin(theme, derived) {
  return `${BANNER}\n\n${renderSkinCss(theme, derived, hero => `url('../assets/${hero}')`)}`
}

/** Build the typed registry both the settings schema and the client read. */
function renderManifest(themes) {
  // Single quotes and bare keys where legal, so the emitted file reads like the
  // hand-written source it replaces and needs no lint exemption.
  const str = value => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
  const key = id => /^[A-Za-z_$][\w$]*$/.test(id) ? id : str(id)
  const rows = themes.map(t => [
    `  ${key(t.id)}: {`,
    `    appearance: '${t.appearance}',`,
    `    chrome: '${t.chrome}',`,
    `    name: { zh: ${str(t.name.zh)}, en: ${str(t.name.en)} },`,
    '  },',
  ].join('\n')).join('\n')
  return `${BANNER}

/** Visual appearance a skin pins the UI to. */
export type SkinAppearance = 'light' | 'dark'

/** Shared component treatment a skin wears (see styles/skins/_chrome.css). */
export type SkinChrome = 'flat' | 'glass' | 'neon'

/** One generated skin's registry entry. */
export interface SkinEntry {
  /** Colour scheme the skin pins, regardless of the light/dark preference. */
  appearance: SkinAppearance
  /** Shared chrome preset the skin wears. */
  chrome: SkinChrome
  /** Display name per supported locale. */
  name: { zh: string; en: string }
}

/** Every generated skin, keyed by id, in registry order. */
export const SKIN_MANIFEST = {
${rows}
} as const satisfies Record<string, SkinEntry>

/** Generated skin ids (the \`none\` stock look is added by theme-settings). */
export type GeneratedSkinId = keyof typeof SKIN_MANIFEST
`
}

/**
 * Emit upstream's parsed palette as data. The browser derives a custom skin
 * from the same numbers this script derives the built-ins from, and it cannot
 * read `design-platform.css` — so the parse result ships as a module.
 */
function renderStock(families, hex, aliases) {
  const num = value => Number(value.toFixed(6))
  const str = value => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
  const steps = family => families[family]
    .map(s => `      { name: '${s.name}', L: ${num(s.L)}, C: ${num(s.C)}, h: ${num(s.h)} },`)
    .join('\n')
  const familyRows = Object.keys(families).sort()
    .map(family => `    '${family}': [\n${steps(family)}\n    ],`).join('\n')
  const hexRows = Object.keys(hex).sort().map(name => `    '${name}': '${hex[name]}',`).join('\n')
  const aliasRows = scheme => Object.keys(aliases[scheme]).sort()
    .map(name => `      '${name}': ${str(aliases[scheme][name])},`).join('\n')
  return `${BANNER.replace('src/styles/skins/themes/<id>.json', 'src/styles/design-platform.css')}

import type { StockData } from '../../../skins/stock.ts'

/**
 * Upstream's palette and semantic layer, extracted from design-platform.css.
 * Regenerating after an upstream palette change is what keeps built-in skins
 * and browser-derived custom skins on the same ramp.
 */
export const STOCK: StockData = {
  families: {
${familyRows}
  },
  hex: {
${hexRows}
  },
  aliases: {
    light: {
${aliasRows('light')}
    },
    dark: {
${aliasRows('dark')}
    },
  },
}
`
}

/** Build the single import entry that replaces per-skin imports in web/base.css. */
function renderIndex(themes) {
  const imports = themes.map(t => `@import './${t.id}.css';`).join('\n')
  return `${BANNER}

/* The shared chrome layer comes first so per-skin palette overrides win at
 * equal specificity, and so the global chrome resets exist exactly once. */
@import '../_chrome.css';
${imports}
`
}

// ── run ─────────────────────────────────────────────────────────────────────

const { families, hex } = readStockPalette()
const aliases = readStockAliases()
const stock = { families, hex, aliases }
const themes = readdirSync(THEMES)
  .filter(f => f.endsWith('.json') && !f.startsWith('_'))
  .map(f => JSON.parse(readFileSync(`${THEMES}/${f}`, 'utf8')))
  // Curated picker order, with id as the tie-break so generation stays stable.
  .sort((a, b) => a.order - b.order || a.id.localeCompare(b.id))

if (themes.length === 0) throw new Error('no themes found')
mkdirSync(OUT, { recursive: true })

const files = new Map()
const audit = []
const failures = []
for (const theme of themes) {
  const derived = deriveSkin(theme, stock)
  files.set(`${OUT}/${theme.id}.css`, renderSkin(theme, derived))

  const row = { skin: theme.id, 明暗: theme.appearance, chrome: theme.chrome }
  for (const entry of auditSkin(theme, derived, stock)) {
    if (entry.ratio === null) { row[entry.label] = '—'; continue }
    row[entry.label] = `${entry.ratio.toFixed(2)}${entry.pass ? '' : ' ✗'}`
    if (!entry.pass) {
      failures.push(`${theme.id} · ${entry.label} ${entry.ratio.toFixed(2)} < ${entry.min}`)
    }
  }
  row['强调校正'] = derived.moved > 0.001 ? `L ${derived.moved.toFixed(3)}` : '—'
  row.hero = theme.hero ? '✓' : '—'
  audit.push(row)
}
files.set(`${OUT}/index.css`, renderIndex(themes))
files.set(`${OUT}/manifest.ts`, renderManifest(themes))
files.set(`${OUT}/stock.ts`, renderStock(families, hex, aliases))

// Deleting a theme file has to delete its sheet too, or the directory stops
// being a function of `themes/` and starts accumulating skins nothing selects.
const orphans = readdirSync(OUT)
  .map(name => `${OUT}/${name}`)
  .filter(path => !files.has(path))

if (check) {
  let drift = 0
  for (const [path, want] of files) {
    let got = null
    try { got = readFileSync(path, 'utf8') } catch { /* missing counts as drift */ }
    if (got !== want) { drift += 1; console.error(`drift: ${path.replace(ROOT, '')}`) }
  }
  for (const path of orphans) { drift += 1; console.error(`残留: ${path.replace(ROOT, '')}`) }
  if (drift > 0) {
    console.error(`\n${drift} 个生成产物与数据源不一致，请跑 build:skins`)
    process.exit(1)
  }
  console.log(`✅ ${files.size} 个生成产物与 ${themes.length} 份主题定义一致`)
} else {
  for (const [path, content] of files) writeFileSync(path, content)
  for (const path of orphans) rmSync(path)
  const swept = orphans.length > 0 ? `，清掉 ${orphans.length} 个残留` : ''
  console.log(`生成 ${themes.length} 个皮肤 → ${files.size} 个文件${swept}\n`)
}

console.table(audit)
if (failures.length > 0) {
  console.error(`\n❌ 可读性契约未达标 ${failures.length} 项：`)
  for (const f of failures) console.error(`   ${f}`)
  process.exit(1)
}
console.log(`\n✅ ${themes.length} 个皮肤 × ${CONTRACT.length + CHROME_CONTRACT.length} 项可读性契约全部达标`)
